### ISSUE TITLE
Encrypt Key doesn't appear in Gmail compose window

### ISSUE THREAD

**Issue by LocutusNX** [fruiz500/PassLok4email#1]
Despite restarting Firefox after installing the addon, the orange encrypt key doesn't appear in the compose email box.

**Comment by fruiz500** [comment]
Thanks for pointing this out. Google had changed some names in Gmail, breaking compatibility with the extension. This has been fixed in version 0.4.3, which I've just submitted. The Chrome store will have it ready in an hour. Mozilla usually takes a couple of days.
